# cloudbuild.yaml - Configuração CI/CD para Cloud Run (SIMPLIFICADO)
steps:
  # Passo 1: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/c09-bot:latest',
      '.'
    ]

  # Passo 2: Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/c09-bot:latest']

  # Passo 3: Deploy no Cloud Run (serviço COMPLETO)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'c09-bot-completo',
      '--image', 'gcr.io/$PROJECT_ID/c09-bot:latest',
      '--region', 'southamerica-east1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '2Gi',
      '--cpu', '1',
      '--timeout', '900s',  # 15 minutos
      '--concurrency', '1',  # Uma execução por vez
      '--max-instances', '1',  # Evita múltiplas instâncias simultâneas
      '--set-env-vars', 'EXECUTION_MODE=COMPLETO',
      '--set-secrets', 'FROTA_USER=frota-user:latest,FROTA_PASSWORD=frota-password:latest,SP_USER=sp-user:latest,SP_PASSWORD=sp-password:latest',
      '--service-account', 'c09-bot@$PROJECT_ID.iam.gserviceaccount.com'
    ]

  # Passo 4: Deploy no Cloud Run (serviço CANDLES)  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'c09-bot-candles',
      '--image', 'gcr.io/$PROJECT_ID/c09-bot:latest',
      '--region', 'southamerica-east1', 
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--timeout', '300s',  # 5 minutos
      '--concurrency', '1',
      '--max-instances', '2',  # Permite 2 instâncias para candles
      '--set-env-vars', 'EXECUTION_MODE=CANDLES',
      '--set-secrets', 'FROTA_USER=frota-user:latest,FROTA_PASSWORD=frota-password:latest,SP_USER=sp-user:latest,SP_PASSWORD=sp-password:latest',
      '--service-account', 'c09-bot@$PROJECT_ID.iam.gserviceaccount.com'
    ]

# Configurações do build
options:
  machineType: 'E2_HIGHCPU_8'  # Máquina mais potente para build
  logging: CLOUD_LOGGING_ONLY

# Timeout total do build
timeout: '1200s'  # 20 minutos